### ISSUE TITLE
Crash on forge server

### ISSUE THREAD

**Issue by adamcirillo** [solidDoWant/ExtraE#1]
[fml-server-2.txt](https://github.com/solidDoWant/ExtraE/files/82390/fml-server-2.txt)
Just tried ExtraE have a crash on my minecraft server client loads up fine and can create new world

**Comment by dootdoot** [comment]
Just fixed it. Am uploading a new release now.

**Comment by solidDoWant** [comment]
Fixed, here's a new release:

http://minecraft.curseforge.com/projects/extrae/files

Thanks for the feedback!
